module.exports = {
  '0': 'Integer number expected',
  '1': 'Real number expected',
  '2': 'Identifier expected',
  '3': 'Element expected',
  '4': '\'+\' operator expected',
  '5': '\'*\' operator expected',
  '6': '\'**\' operator expected',
  '7': '\'(\' expected',
  '8': 'Closing parentheses, square brackets or braces are missing.',
  '9': '\'$\' operator expected',
  '10': '\',\' expected',
  '11': '\'.\' expected',
  '12': '\';\' expected',
  '13': '\'++\' operator expected',
  '14': 'relational operator expected - LT GT EG NE LE GE  <  >  =  <> <= >=',
  '15': 'OR operator expected',
  '16': 'INF expected',
  '17': 'SUM operator expected',
  '18': '\'parameter\' expected',
  '19': '\'and\' expected',
  '20': '\'not\' operator expected',
  '21': '\'all\' expected',
  '22': '\'positive\' expected',
  '23': '\'elseif\' expected',
  '24': '\'else\' expected',
  '25': '\'loop\' expected',
  '26': '\'table\' expected',
  '27': '\'alias\' expected',
  '28': '\'solve\' expected',
  '29': '\'using\' expected',
  '30': '\'option\' expected',
  '31': '\'display\' expected',
  '32': 'ORD expected',
  '33': 'CARD expected',
  '34': '\'model\' expected',
  '35': '\'minimizing\' or \'maximizing\' expected',
  '36': 'The two dots .. are missing in the equation definition.',
  '37': 'The equation type (eg. =L=) is missing in the body of the equation.',
  '38': 'Double or single quote expected',
  '39': 'Colon \':\' expected',
  '40': '\'if\' expected',
  '41': '\'while\' expected',
  '42': '\'for\' expected',
  '43': '\'do\' expected',
  '44': '\'then\' expected',
  '45': '\'until\' expected',
  '46': '\'end...\' expected',
  '50': 'Loop controlling index appears in model equation(s)',
  '51': 'There are prohibited nonlinear expressions.',
  '52': 'There are prohibited nonlinear expressions.',
  '53': 'There are prohibited nonlinear expressions.',
  '54': 'There are prohibited nonlinear expressions.',
  '55': 'There are prohibited nonlinear expressions.',
  '56': 'There are prohibited nonlinear expressions.',
  '57': 'There are prohibited nonlinear expressions.',
  '58': 'There are prohibited nonlinear expressions.',
  '59': 'There are prohibited nonlinear expressions.',
  '60': 'There are prohibited nonlinear expressions.',
  '61': 'Functions with discontinuous derivatives are illegalIn nlp models. use "dnlp"',
  '62': 'Endogenous lag operations are illegal',
  '63': 'Functions illegal in model equations - normal, uniform, jnow ....',
  '64': 'Function called with non constant argument',
  '65': 'Discrete variables can only appear in MIP, RMIP, MINLP  RMINLP MIQCP or RMIQCP MPEC RMPEC problems.',
  '66': 'A data item which has not been given numerical values appears in an equation.',
  '67': 'This symbol is not allowed for this type of solution',
  '68': 'Variables are only allowed in equ.var pairs for MCP, CNS, MPEC, RMPEC',
  '69': 'Dimension of variable is unknown',
  '70': 'The dimensions of the equ.var pair do not conform',
  '71': 'The equation has been declared, but not defined.',
  '72': 'A variable reference can only follow an equation in an MCP',
  '73': 'Incorrect substitution symbol in %xxx.yyy%   GAMS.yyy or SYSTEM.yyy or xxx.HEAD or xxx.TAIL',
  '74': 'An undefined procedure has been encountered in a model list',
  '75': 'This procedure call makes the model nonlinear',
  '76': 'An Equation has been referenced by a procedure but does not   exist in the model list. You need to add this equation to   the model list',
  '77': 'The second argument in the function POWER has to evaluate   to an integer constant',
  '78': 'Domains on equ.var pair are inconsitent',
  '79': 'The third (last) argument has to evaluate to a constant',
  '80': 'A \'..\' expected for equation specification',
  '81': 'A \'=\' expected for assignment statements. Alternative   assignment operators are \'$=\' and \':=\'.',
  '92': 'CTRL-Z character encountered in source file. This character is  sometimes uploaded from MS-DOS systems. Correct the input  or use the GAMS parameter CTRLZ. \'GAMS input CTRLZ=1 ....\' will  treat the CTRL-Z character as a blank.',
  '93': 'A set has to be indexed when used on the left side',
  '94': 'Sign illegal with acronyms, \'na\' and \'eps\'',
  '95': '\'yes\' or \'no\' not allowed here',
  '96': 'A statement followed by another statement is not terminated with ;.',
  '97': 'A statement followed by another statement is not terminated with ;.',
  '98': 'Non-blank character(s) beyond max input line length (40000)  (check that each line ends with a carriage return)',
  '99': 'Character is illegal in gams input - reset to blank',
  '100': 'Tab character is illegal - reset to blank   you may want to use the gams parameter \'tabin\' to   enable tab expansion. for example: \'tabin 8\' will   use tab positions 1,17,25,......      >gams input .... tabin=8 ...',
  '101': 'Line overflow because of tab expansion - line truncated',
  '102': 'Too many digits in integer number',
  '103': 'Too many digits in number   $offdigit can be used to ignore trailing digits',
  '104': 'Exponent expected',
  '105': 'Exponent out of range   $offdigit can be used to replace large numbers with UNDF',
  '106': 'abs(number) out of range   $offdigit can be used to replace large numbers with UNDF',
  '107': 'Symbol too long',
  '108': 'Suffix identifier too long',
  '109': 'Identifier/Element too long',
  '110': 'Too many decimal points in a number',
  '111': 'Wrong suffix on variable assignment - allowable are   l     level (activity)   m     marginal (reduced cost)   lo    lower bound   up    upper bound   scale variable scale   prior priority for MIPs   fx    fix level, lower and upper at same value',
  '112': 'Wrong suffix on equation reference - allowable are   l     level (activity)   m     marginal (reduced cost)   lo    lower bound   up    upper bound   scale variable scale',
  '113': 'Wrong suffix on model - allowable are1. model specific run time options - will override global   bratio, cheat, cutoff, dictfile, domlim, holdfixed   integer1..integer5, iterlim, limcol, limrow, nodlim   optca, optcr, optfile, prioropt, real1..real5, reform   reslim, savepoint, scaleopt, solprint, solvelink, solveopt   sysout, threads, tolinfeas, tolinfrep, tolproj, tryint   trylinear, workfactor, workspace2. set by gams after each solve execution   domusd, etalg, etsolve, etsolver, handle, iterusd, line   linkused, modelstat, nodusd, number, numdepnd, numdvar   numequ, numinfes, numnlins, numnlnz, numnopt, numnz   numredef, numvar, numvarproj, objest, objval, procused   resgen, resusd, robj, solvestat, suminfes',
  '114': 'Closing quote missing in element',
  '115': 'Label is unknow in symbolic equation   You may change this error with $onwarning/offwarning   to a warning message or do not use ON115=1',
  '116': 'Label is unknown',
  '117': 'Domain checking suppressed for this symbol',
  '118': 'Unrecognized statement',
  '119': 'Number (primary) expected',
  '120': 'GAMS cannot find a set with this name. Check for typos in the set name and set elements that are referenced without quotes.',
  '121': 'Set expected',
  '122': 'One dimensional set expected',
  '123': 'Set has not been initialized and the dimension is unknown',
  '124': 'Suffix for a set not allowed',
  '125': 'The set is controlled more than once, e.g., by an indexed operation like sum and by an equation definition.\t',
  '126': 'Set identifier or \'(\' expected',
  '127': 'Base of power not a real number',
  '128': 'Exponent of power not a real number',
  '130': 'Division not defined for a set',
  '131': 'Incompatible operands for multiplication',
  '133': 'Incompatible operands for addition',
  '135': 'Incompatible operands for relational operator',
  '136': 'Aliased redefinition of loop controlled set (map)',
  '139': 'Wrong suffix on file - allowable are   ps, pw, bm, tm  (page options)   cr, cc, ll      (current curser)   tw, tj, tf      (text options)   lw, lj          (label options)   sw, sj          (set options)   nw, nj, nd, nz  (number options)   tlcr, tlcc, tlll   (title curser)   hdcr, hdcc, hdll   (header curser)   lp, pc, ap, case   (file options)',
  '140': 'GAMS is looking for a keyword or declared item and cannot find it. Check spelling and declarations.',
  '141': 'The parameter without data is used or problems with solve and therefore attributes .l and .m are empty.',
  '142': 'No suffix allowed here - suffix ignored',
  '143': 'A suffix is missing',
  '144': 'Illegal identifier (model or function)',
  '145': 'Set identifier or quoted element expected',
  '146': 'Maximum number of dimensions exceeded',
  '147': 'Real value for lag operator expected',
  '148': 'The identifier is referenced with more or less indexed sets than in the declaration.',
  '149': 'The set is not controlled, neither by an indexed operation like sum, nor by an equation definition, nor by a loop or similar.',
  '150': 'Symbolic equations redefined',
  '151': 'The left and right side are of different type in an assignment   use $conditions to convert or $ONMIXED',
  '152': 'The expression is set valued - not allowed in equations   use $conditions to convert or $ONMIXED',
  '153': 'Uncontrolled set(s) in lag-expression',
  '154': 'Set for \'ord\' is not controlled',
  '156': 'Inconsistent identifier (set) in alias list',
  '157': 'No known set found in alias list',
  '158': 'No aliased symbol found',
  '159': 'An aliased set is not allowed here   aliased sets can only be used for indexing and   cannot be assigned or used as operands.',
  '160': 'Unique element expected - a starting symbol was encountered   and parsing will continue by entering \'element\'.   An UNQUOTED element has to start with a letter or digit   followed by letters, digits, \'+\', \'-\' or \'_\'. The length   is limited to 63 characters. The following words are   reserved (starting symbols of a GAMS statement) and cannot   be used for UNQUOTED set elements:      ABORT, ACRONYM(S), ALIAS, BINARY, DISPLAY, ELSE      EQUATION(S), EXECUTE, FILE(S), FOR, FREE, IF, INTEGER, LOOP      MODEL(S), NEGATIVE, OPTION(S), PARAMETER(S)      POSITIVE, PROCEDURE(S), PUT, PUTCLEAR, PUTCLOSE, PUTHD      PUTPAGE, PUTTL, SCALAR(S), SEMICONT, SET(S), SOS1, SOS2      TABLE, VARIABLE(S), WHILE   QUOTED elements can contain any character. Single and   double quotes can be used (starting and ending quote have   to match).',
  '161': 'Conflicting dimensions in element',
  '162': 'The variant part of the macro label contains a non-digit',
  '163': 'Too many digits in numeric part of macro',
  '165': 'First number greater than second number in macro-or- more digits in first number than second (eg x01*x9)-or- leading zero illegal on second number (eg x1*x010)',
  '166': 'A table must have two or more dimensions - use parameter list   rest of table will be ignored',
  '167': 'Redefinition of loop controlled set (map)',
  '168': 'Assignment not allowed to this identifier',
  '169': 'Equation definition within a LOOP or IF statement not allowed',
  '170': 'The referenced set element cannot be found in the set defined for this index position. Check for typos, omissions in the set declaration, missing quotes and references to the wrong set.',
  '171': 'A domain error. The wrong set is referenced for the respective index position.',
  '172': 'Element is redefined',
  '174': 'Symbol is not a set',
  '175': 'A map with the same name is already active',
  '176': 'A row with the same name has been defined before in this table.',
  '179': 'A \'(\' was expected - insert and continue',
  '180': '\'variable\' expected',
  '181': 'Closing \'/\' missing in scalar statement',
  '182': 'Closing \'/\' missing in a set, parameter or model statement',
  '183': 'Closing \'/\' missing in file statement',
  '184': 'Domain list redefined',
  '185': 'Set identifier or \'*\' expected',
  '186': 'Illegal data list ignored',
  '187': 'Assigned set used as domain',
  '188': 'Assigning to this set is NOT allowed. The set may have been   used in a domain definition or is a predefined/readonly set.',
  '189': 'Domain list not allowed for scalar, acronym or model',
  '190': 'Text too long, max is 255 characters',
  '191': 'Closing quote missing',
  '192': 'Identifier or quoted string expected',
  '193': 'Text for symbol redefined',
  '194': 'Symbol redefined - a second data statement for the same symbol   or a data statement after an assignment',
  '195': 'The name used here was already used for another identifier.',
  '196': 'Variable redefined with a different subtype',
  '197': 'Lag or \'ord\' illegal with non constant set   $offOrder allows lag operations on dynamic sets, reset with $onOrder   or use of a * universe',
  '198': 'Using the operation ord or a lag/lead operation with a set that is not ordered.',
  '199': 'Assigning to set used in \'ord\' or lag   this statement changes the content of a set   previously used with \'ord\' or lag/lead.',
  '200': 'Function not allowed here',
  '201': 'Invalid argument for function',
  '202': 'Too many arguments for function',
  '203': 'Too few arguments for function',
  '205': 'Missing dollar control option',
  '206': 'A phantom cannot be redefined',
  '207': 'A phantom element must have a zero value',
  '208': 'Missing phantom element',
  '209': 'An existing element cannot be used as phantom element',
  '210': 'Unknown dollar control option',
  '211': 'Left margin must be less than right margin',
  '212': 'Left margin can not be less than 1',
  '213': 'Right margin must be greater than left margin and 15',
  '214': 'Right margin must be less than 256',
  '215': 'Unknown dollar debug option. valid are -  dmpsym dmpcpl dmptpl dmpins measure tabteston tabtestoff  memorystat domteston domtestoff dmplim dmpunits',
  '216': 'No previous "ontext"',
  '217': '"offtext" expected',
  '218': 'Dollar and comment characters must be different',
  '219': 'Single character between blanks expected',
  '220': 'Partial overlapping column adjusted',
  '221': 'Total overlapping column ignored',
  '222': 'Row dimension inconsistent with declared dimension and column dimension',
  '223': 'Overlapping row name',
  '224': 'Overlapping entry ignored',
  '225': 'Floating entry ignored',
  '226': 'Multiple entry ignored',
  '227': '$label has been defined previously in this file',
  '228': 'Column dimension has changed',
  '229': 'Row dimension has changed',
  '230': 'Identifier is not a model',
  '233': 'Empty model list no legal data between / / or \'all\' without any equations',
  '234': 'Illegal type in model list - equation or equation.variable  or another model list',
  '235': 'Table text terminated with illegal character \'/\' or \',\'',
  '236': 'Duplicate identifier(s) in model definition',
  '240': 'The suffix .te can only be used with sets in a put list',
  '241': 'Model has not been defined',
  '243': 'Objective is not a variable',
  '244': 'Unknown or missing processor (LP,MIP,...)',
  '245': 'Objective variable not referenced in model',
  '246': 'Objective variable is not a free variable',
  '247': 'No algorithm available for this class of model',
  '250': 'Unknown option.  valid are -  lp = "lpname" (and for nlp, dnlp, mip, rmip etc)  integer1 to integer5    seed  limrow  limcol  domlim  iterlim  work (integer values)  decimals                              (0..8)  optca optcr  real1 to real5   reslim  bratio       (real values)  measure  eject                        (no values)  sysout   solprint                     (on/off)  solveopt                              (merge/replace)  sparseopt                             (safe/fast)  sparserun                             (on/off)  "symbol":decimals:rows:columns        (display control)  (decimals, rows, columns are integers. Number of   displayed decimal places, labels for each row and   for each column)',
  '251': 'Unknown option value',
  '252': 'System option value too large',
  '253': 'Unknown algorithm   The GAMS statement \'option subsystems;\' will list   the installed subsystems in the GAMS listing file.',
  '254': 'Algorithm not licensed',
  '255': 'Algorithm not suitable for process',
  '256': 'Something is wrong with the model specification. This is often a consequential error of another error. Look for other error messages immediately after the solve statement.',
  '257': 'The solver is not checked. This may be a consequential error of any GAMS error.',
  '258': 'Option "decimals" must be in range 0..8',
  '259': 'A mapping set with the suffix .TL has to have a dimension of one',
  '260': 'Too many instructions to compile(split your file into 2 parts and use save then restart)',
  '261': 'The suffix .TL can only be used in a PUT statement on   a controlling set or on a one dimensional map, for example:   loop(tt(t), put tt.tl t.tl .. );',
  '262': 'Minimizing/Maximizing does not apply to this model type',
  '265': 'Equation has not been defined',
  '266': 'Identifier is not an equation',
  '267': 'A variable appeared more than once in and equ.var pair',
  '269': 'A hercules or sambal model must contain 3 identifiers',
  '270': 'A matbal model must contain 5 identifiers',
  '271': 'Illegal type (not set, parameter, variable or equation)',
  '272': 'Dimension not known',
  '273': 'Display format specification must have 1 or 3 sub-fieldsRequired format is :- option "symbol":decimals:rows:columns; -or- option "symbol":decimals; decimals: in range 0..8  (ignored for a set) rows:     0  forces display into list format   -or-    1..(dimension-1)  number of labels on each row columns:  max number of columns across page if row spec is 0   -or-    1..(dimension-rows)  number of labels each column',
  '274': 'Inconsistent values for display specificationRequired format is :-  option "symbol":decimals:rows:columns;  -or- option "symbol":decimals; decimals: in range 0..8  (ignored for a set) rows:     0  forces display into list format   -or-    1..(dimension-1)  number of labels on each row columns:  max number of columns across page if row spec is 0   -or-    1..(dimension-rows)  number of labels each column',
  '275': 'This set is used already as an indexing map and can only be used  as a reference. No additional indexing is possible.  For example, x(link(i,j),link(ii,jj)) = .... is incorrect  because link now serves as a driving index',
  '276': 'Invalid external name specified - one of the following applies  invalid file name syntax -or-  name is already used  -or-  name is same as input or output file name  -or-  a file name from save files is no longer valid due to the above',
  '277': 'A controlled index cannot become a map',
  '278': 'Lags are not allowed on maps',
  '279': 'Map has been redefined',
  '280': 'Include/insert filename already in use   $onrecurse will allow recursive includes',
  '281': 'Maximum include file nest level exceeded',
  '282': 'Unable to open include file',
  '283': 'Expecting external file name as  $include name or "name" or \'name\'',
  '284': 'Missing error mark',
  '285': 'Illegal selection of in-line/end-of-line comment delimiter(s)conflicts with other special characters',
  '286': 'Invalid in-line/end-of-line comment delimiter specification       single delimiter -  $inlinecom { }                        -  $eolcom # -or-  double delimiter -  $inlinecom /* */                        -  $eolcom _$This file may have inherited the same comment character(s).For example use: $offeolcom $offinline $eolcom !',
  '287': 'In-line comment still active at end of main or included input file',
  '288': 'Opening in-line comment equal to eol comment',
  '290': 'Width of put field cannot be set valued',
  '291': 'Decimals for put field cannot be set valued',
  '292': 'Unknown justification type',
  '293': 'No external file has been declared',
  '294': 'No external file assigned - A file has to be made current by    using the name on a put statement, i.e. PUTxxx fname ....',
  '295': 'Expression for row or column address has to be real',
  '296': 'Wrong or missing system suffix - allowable are   date,elapsed,fe,filesys,fn,fp,gstring,ifile,iline,incline,   incname,incparent,incparentl,lice1,lice2,line,listline,   memory,ofile,opage,page,pfile,platform,prline,prpage,   rdate,redirlog,rfile,rtime,sfile,sstring,tclose,tcomp,   texec,time,title,tstart,verid,version,   LP,NLP,MIP,....',
  '297': 'Suffix not allowed here',
  '298': 'Wrong suffix for this type',
  '299': 'Unexpected end of file',
  '300': 'Remaining errors not printed for this line',
  '301': 'Batch include parameter too long',
  '302': 'Batch include substitution line exceeded maximum input length',
  '303': 'Dollar control directive only valid in batch include files   Use $BATINCLUDE instead of $INCLUDE.',
  '304': 'Expecting label identifier',
  '305': '$label, $ifthen $elseif $else $endif must be first dollar control   statement on a single line',
  '306': 'Unresolved goto label',
  '307': 'Apparent infinite loop. Too many $goto jumps to a $label   This can be reset with $maxgoto n (default is 100).',
  '308': 'Expected a complete $if/ifthen/elseif  conditional on the same line.The statement can be placed on the next line as shown below:  $IF [NOT] condition statements  $IF [NOT] condition  statements',
  '309': 'No keyword found assume comparison expression : string1 == string2  $IF [NOT] condition statement  condition ::= EXIST      filename                ERRORLEVEL n                ...                string1 == string2',
  '310': 'Set identifier or * expected',
  '311': 'The function ord(\'string\',expr) needs the second argument   Note that ord(\'string\') does NOT return the ordinal position   of the label \'string\'. ord(\'string\',n) return the ordinal   value of the n\'th character in \'string\'.',
  '312': 'This version of GAMS is too old to run this program',
  '313': 'The .fx suffix can only be used on the left side - ignored',
  '314': 'Use this suffix only in put statements - ignored',
  '315': 'Unknown suffix - ignored',
  '316': 'Implied type inconsistent with previous use of symbol',
  '317': 'Completely inconsistent type implications',
  '318': 'Domain list redefined - no previous domain list - * assumed   when data was associated with this symbol',
  '319': 'Set must be defined to be used as a domain',
  '320': 'An aliased set cannot be redeclared',
  '321': 'A \'(\' following an \'IF\' is missing. We assumed you wanted to writean if-statement. This statement has been introduced with GAMS 2.25and it is possible that \'if\' was used as an identifier.The GAMS parameter G205=1 can be used to run with the old syntax.',
  '322': 'Wrong complementarity pair. Has to be equ.var.',
  '323': 'Priorities can only be used on discrete variables',
  '324': 'Scales cannot be applied to discrete variables',
  '325': 'Body of table missing - a \';\' terminates a statement',
  '326': 'An empty table statement is not followed by a legal statement',
  '327': 'A $goto in an active $onverbatim section',
  '328': 'Wrong suffix on equation assignment - allowable are   l     level (activity)   m     marginal (reduced cost)   lo    lower bound   up    upper bound   scale equation scale',
  '329': 'Wrong suffix on variable reference - allowable are   l     level (activity)   m     marginal (reduced cost)   lo    lower bound   up    upper bound   scale variable scale   prior priority for MIP   slacklo,slackup,slack, slack values   infeas infeasibility',
  '330': 'CALL failed',
  '331': 'Parameters longer than 255 characters',
  '332': '$Warning encountered - see listing for details',
  '333': '$Error encountered - see listing for details',
  '334': 'Illegal data following a data element - rest ignored',
  '335': 'Complimentarity pair equ.equ has to have the same names',
  '336': 'This version of GAMS does not allow the declaration of   variables and equations. It is intended to run precompiled   models only. If you need a fully licensed GAMS system contact   your distributor or GAMS Development Corporation.',
  '337': 'A set has been domain-checked by itself but has more than   one dimension.   SET I(I) / a,b,c /;',
  '338': 'Unique element expected - symbol was not an element   and the following text will be skipped until a proper   symbol is found to recover. Remember that an UNQUOTED   element has to start with a letter or digit   followed by letters, digits, \'+\', \'-\' or \'_\'. The length   is limited to 63 characters. The following words are   reserved (starting symbols of a GAMS statement) and cannot   be used for UNQUOTED set elements:      ABORT, ACRONYM(S), ALIAS, BINARY, DISPLAY, ELSE      EQUATION(S), EXECUTE, FILE(S), FOR, FREE, IF, INTEGER, LOOP      MODEL(S), NEGATIVE, OPTION(S), PARAMETER(S)      POSITIVE, PROCEDURE(S), PUT, PUTCLEAR, PUTCLOSE, PUTHD      PUTPAGE, PUTTL, SCALAR(S), SEMICONT, SET(S), SOS1, SOS2      TABLE, VARIABLE(S), WHILE   QUOTED elements can contain any character. Single and   double quotes can be used (starting and ending quote have   to match).',
  '339': 'Option PROFILE=n cannot be used inside a loop.',
  '340': 'Probably the quotes in a set element reference are missing.',
  '341': 'Symbol/ident missing in $IF [NOT] DECLARE/DEFINED statement   Line has been ignored',
  '342': 'Illegal suffix syntax - has to start with a letter',
  '343': 'Abort triggered by above statement',
  '344': 'SMIN or SMAX not allowed on set valued expressions, use',
  '345': '   PROD and SUM instead.',
  '346': 'The file name exceeds the maximum length -  Name truncated   Use \'GAMS fn DP=2 ..\'  to get trace of file operations   on the screen or logfile.',
  '347': 'Uncleared gstring overflow condition. A string was truncated   and no other error trap was triggered. Most likely   a file name operation. You may want to use \'GAMS fn DP=2 ..\'   to get trace of file operations',
  '348': 'The external file name is too long',
  '349': 'Declaration not allowed inside a LOOP or IF statement',
  '350': 'Unmatched parenthesis types. For example ( } or [ }',
  '351': '   checking suppressed for the remainder of this statement',
  '352': 'Set has not been initialized',
  '353': 'The domain for this index position is unknown and the element   cannot be checked at this point. Missing data statement.',
  '360': 'Current maximum error',
  '361': 'Values for domain 1 are unknown - no checking possible',
  '362': 'Values for domain 2 are unknown - no checking possible',
  '363': 'Values for domain 3 are unknown - no checking possible',
  '364': 'Values for domain 4 are unknown - no checking possible',
  '365': 'Values for domain 5 are unknown - no checking possible',
  '366': 'Values for domain 6 are unknown - no checking possible',
  '367': 'Values for domain 7 are unknown - no checking possible',
  '368': 'Values for domain 8 are unknown - no checking possible',
  '369': 'Values for domain 9 are unknown - no checking possible',
  '370': 'Values for domain 10 are unknown - no checking possible',
  '371': 'The procedure is still undefined - rest of statement ignored',
  '372': 'Not of the form EQU=VAR, VAR not of type variable',
  '373': 'Equation names without a suffix are only allowed for returnarguments with variable capability',
  '374': 'Wrong type for Procedure definition',
  '375': 'Unit does not exist',
  '376': 'Function does not exist',
  '377': 'Unit name missing',
  '378': 'This argument cannot be called with a set',
  '379': 'This argument cannot be called with a constant',
  '380': 'Cannot be called with a variable type',
  '381': 'EQU=VAR pair only allowed on returns with variable capability',
  '382': 'Dimensions of argument does not match or is not known',
  '383': 'Cannot bind arguments -  missing / .. / or proc(....) needed',
  '384': 'Missing or incorrect argument definition inherited',
  '385': 'Too many argument on this call',
  '386': 'Inconsistent domains on position 1',
  '387': 'Inconsistent domains on position 2',
  '388': 'Inconsistent domains on position 3',
  '389': 'Inconsistent domains on position 4',
  '390': 'Inconsistent domains on position 5',
  '391': 'Inconsistent domains on position 6',
  '392': 'Inconsistent domains on position 7',
  '393': 'Inconsistent domains on position 8',
  '394': 'Inconsistent domains on position 9',
  '395': 'Inconsistent domains on position 10',
  '396': 'Missing domain data',
  '397': 'Missing data for input argument(s)',
  '398': 'Unknown output dummy parameter for deriv=output.input',
  '399': 'Unknown input dummy parameter for deriv=output.input',
  '400': 'Missing input dummy parameter for deriv=output.input',
  '401': 'Dimensions for deriv=output.input do not match',
  '402': 'Input dummy parameter for deriv=output.input not a variable input',
  '403': 'Output dummy parameter for deriv=output.input not an equation output',
  '404': 'Derivative output not allowed in /...../ form',
  '405': 'Too few arguments on this call',
  '406': 'More than one key set (known set) in alias statement',
  '407': 'ELSE clause without a matching IF statement - ELSE ignored',
  '408': 'Surplus closing parentheses, square brackets or braces.',
  '409': 'Unrecognizable item, likely you missed a ; in the previous line.',
  '410': 'Wrong suffix on procedure - allowable are   rc cptime stacksize temp domcount derivnoise derivstep   derivtype',
  '411': 'Procedure argument error - deriv=out.in:ident   not an ident',
  '412': 'Same derivative has been referenced twice - dropped',
  '413': 'This equation has been defined with a \'..\' statement and  cannot bee used anymore with the equ=var format',
  '414': 'This equation has been used in a procedure with the  equ=var form and cannot be redefined with \'..\'',
  '415': 'This equation can only be used together with a procedure  because of the equ=var format',
  '416': 'Library name missing on INSERT statement',
  '417': 'File name missing on INSERT statement',
  '418': 'Unable to open INSERT file',
  '419': 'Library name has been used before - insert ignored',
  '420': 'The Insert header file is inconsistent with previous use   The time stamp does not match. You can use $DEBUG DMPUNITS   to get a summary of inserted definitions.',
  '421': 'Unable to load header file   Need better messages for this',
  '422': 'New library different from old one',
  '423': 'New procedure different from old one',
  '424': 'Procedure previously defined',
  '425': 'Cannot override exiting bindings, only derivative requests are   allowed',
  '426': 'Arguments not checked because of other errors',
  '427': 'Incorrect insert header file',
  '428': 'Don\'t allow suffix - only type parmeter allowed',
  '429': 'Don\'t allow suffix notation for output arguments in / .... /',
  '430': 'Cannot $KILL,$CLEAR or $SLICE a symbol with a .suffix',
  '431': 'Illegal symbols in $SLICE command',
  '432': 'Missing information on $SLICE line',
  '433': 'Slice reference not terminated with \')\'',
  '434': '$SETxxx id - id missing',
  '435': '$SETARG ... last cannot hold all remaining arguments',
  '436': '%xxxxx% not defined',
  '437': 'CTRL-M character encountered in source file. This character is  sometimes uploaded from MS-DOS systems. Correct the input  or use the GAMS parameter CTRLM. \'GAMS input CTRLM=1 ....\' will  treat the CTRL-M character as a blank.',
  '438': 'Linefeed character encountered in source file. Most likely you  are using a UNIX style file with the CR (control^M) missing.',
  '439': 'FOR index variable has to be a scalar',
  '440': 'Expression has to be real valued',
  '441': 'Expected TO or DOWNTO. The general syntax of a FOR statement is  FOR ( i = start TO/DOWNTO end [BY increment] , statements )',
  '442': 'Expected a \',\' or BY. The general syntax of a FOR statement is  FOR ( i = start TO/DOWNTO end [BY increment] , statements )',
  '443': 'FOR index variable already in use by other FOR statement',
  '444': 'SYSTEM.xxx in DISPLAY statement not implemented',
  '445': 'More than one operator in a row. You need to use parenthesis  if you want to use such statements. For example      x := x + - not y;  ->  x := x + (- (not y));      sum(i$not x, ..)   ->  sum(i$(not x),..)',
  '446': 'Incompatible operation on AND or OR. The flag $ONMIXED and   $OFFMIXED can be used to permit mixed mode expressions.',
  '447': 'ident in EXECUTE statement not implemented',
  '448': '%GAMS.xxxxx%, unknown xxxxxx - no substitution',
  '449': '%SYSTEM.xxx%, unknown xxxxxx - no substitution   date,elapsed,errorlevel,fe,filesys,fn,fp,gstring,ifile,iline,   incline,incname,incparent,incparentl,lice1,lice2,line,listline,   memory,ofile,opage,page,pfile,platform,prline,prpage,   rdate,redirlog,rfile,rtime,sfile,sstring,tclose,tcomp,   texec,time,title,tstart,verid,version,   LP,NLP,MIP,....',
  '450': 'Symbol following $IF [NOT] xxx id not an ident',
  '451': 'Expecting and integer following $IF DIMENSION n',
  '452': 'Identifier, * or . expected',
  '453': 'Assignment to this parameter not allowed. This is a predefined   readonly parameter type.',
  '454': 'Reached EOL in a delimited data record while reading a label',
  '455': 'Bad or missing delimiter while reading delimited data records',
  '456': 'The dimension has to be known if you want to use $ONDELIM   for a SET, PARAMETER or TABLE data statement. $ondelim will   be ignored for this section.',
  '457': 'More than one entry on data line',
  '458': '$echo must have redirection symbol > or >>',
  '459': '$echo file cannot be opened',
  '460': 'Empty data statements not allowed. You may want to use $ON/OFFEMPTY',
  '461': 'Cannot have empty data statement without knowing dimension',
  '462': 'The row section in the previous table is missing',
  '463': 'The column section in the previous table is missing',
  '464': 'Looking for more data - illegal delimiter or missing data entries   more column entries than data entries in this row',
  '465': 'Too much data on this line - rest ignored',
  '466': 'Number expected - rest of line ignored',
  '467': 'Wrong end statement - \'endif\' expected',
  '468': 'Unexpected symbol encountered - this will terminate the loop  Symbol replace by \'endloop\'',
  '469': 'Wrong end statement - \'endwhile\' expected',
  '470': 'Wrong end statement - \'endfor\' expected',
  '471': 'Inlinecomment on $Include is not closed   terminating comment symbol inserted before   entering include file',
  '472': 'Too many delimiters',
  '473': 'Nonblank entries following the number',
  '474': 'Missing number in delimited data line',
  '475': 'Expecting and integer following $IF ERRORLEVEL/GAMSVERSION n',
  '476': 'Scale not allowed on =X= equation type',
  '477': 'Cannot assign to predefined symbol',
  '478': 'Column section under ondelim must be of dimension = 1',
  '479': 'Can only KILL/CLEAR SCLICE sets, parameters, variables   and equations.',
  '480': 'The second argument in the function POWER has to evaluate   to an integer constant.',
  '481': 'Suffix TMODSTAT and TSOLSTAT only valid with models',
  '482': 'A mapped variable cannot be an objective variable',
  '483': 'Mapped variables have to appear in the model',
  '484': 'Unmapped MCP equations cannot be =g= =l= or =n=',
  '485': 'Cannot get interactive console under the IDE',
  '486': 'Wrong suffix for CARD(id.suf)   no suffix or .TE .TL .TS',
  '487': 'Set \'id\' for CARD(id.TL) or CARD(id.TE) is not controlled',
  '488': 'Wrong suffix for ORD(id.suf,expr)   no suffix or .TE .TL .TS',
  '489': 'Cannot load/unload this symbol and type',
  '490': 'Cannot load/unload this suffix',
  '491': 'Cannot Unload symbol with unknown dimension',
  '492': 'Symbol not in GDX',
  '493': 'Alias cannot receive data',
  '494': 'Load types are different',
  '495': 'Load dimension are different',
  '496': 'Load/unload ident expected',
  '497': 'Problems closing GDXIN',
  '498': 'Problems opening GDXIN: Unknown',
  '499': 'Problems opening GDXOUT: Unknown',
  '500': 'Problems closing GDXOUT',
  '501': 'GDXOUT file not open - ignore rest of line',
  '502': 'GDXIN  file not open - ignore rest of line',
  '503': 'Problems dumping all symbols',
  '504': 'Could not unload this symbol',
  '505': 'Errors encountered after processing EOF',
  '506': 'This symboltype is illegal in MCP model list',
  '507': 'This name does NOT match the previous name',
  '508': 'Blank needed between element and text  (-or- illegal character in element)',
  '509': 'Dollar control statements are processed during compilation   and NOT during execution. The use of dollar statements   that change data may be misleading when inside a LOOP   or IF statement.',
  '510': 'Unable to open gdx file for $GDXIN',
  '511': 'An Excel range has to go from low to high',
  '512': 'Element expected but closing \'/\' found',
  '513': 'Unable to open gdx file for $GDXOUT',
  '514': 'Unknown string %xxx.yyyy%',
  '540': 'Echo not allowed under this execution mode',
  '541': 'Echo into this location not allowed under this execution mode',
  '542': '$call not allowed under this execution mode',
  '543': 'execute not allowed under this execution mode',
  '544': 'Illegal diff symbol',
  '545': 'Cannot diff symbol without data',
  '546': 'Unmatched diff symbols',
  '547': 'Diff symbols with different dimensions',
  '548': 'Includes are not allowed under this execution mode',
  '549': 'Includes to this location are not allowed under this execution mode',
  '550': 'Unknow symbol in Security list',
  '551': 'Cannot have Security item with suffix',
  '552': 'Cannot use protected symbol on left side',
  '553': 'Cannot clear/kill protected symbol',
  '554': 'Cannot import data for a protected symbol',
  '555': 'Cannot slice a protected symbol',
  '556': 'Protected symbol cannot have data statements',
  '557': 'Protected symbols encountered in ALL',
  '558': 'Protected symbols encountered in model list',
  '559': 'Cannot solve protected model',
  '560': 'Model contains purged symbol',
  '561': 'System not licensed to use this feature',
  '562': 'Identifier locked by previous privacy activity',
  '563': 'external Procedure with a library',
  '564': 'no previous \'onecho\'',
  '565': '\'offecho\' expected',
  '566': 'Cannot gdx this item',
  '567': 'No suffix for SET PARAMETER or ACRONYM allowed',
  '568': 'Missing ident following READABLE',
  '569': 'Only the first argument can be quoted (external file name)',
  '570': 'GDX ident expected - the list items can take the form   \'gams_name\'  or \'gams_name=gdx_name\'. Check for   a missing \';\'',
  '571': 'No suffix allowed on GDX ident',
  '572': 'Cannot GDX load/unload this type - only sets, parameters   equations and variables can be used',
  '573': 'Cannot load/unload symbol with unknown dimension',
  '574': 'You have redefined a built in function that has notbeen used before. You can use this function by prefixingits name by \'system.\'',
  '575': 'You have redefined a built in function that has beenused before. You still can use this function by prefixingits name by \'system.\'',
  '576': 'Errors have been cleared and made into warnings  execution of this program may fail in unpredictable ways',
  '577': 'The multiple declaration data is not ordered',
  '578': 'The merging of existing and new data results in an unordered set',
  '579': 'Cannot clear a set used as a domain or used in log/ord operations',
  '580': 'Cannot clear a symbol with unknown dimension',
  '581': 'Cannot clear a read only symbol',
  '582': '$SETNAMES without arguments',
  '583': '$SETNAMES has too many arguments',
  '584': '$SETCOMPS without arguments',
  '585': 'Bad suffix on gdx namne',
  '586': 'Gams symbol is a variable and has no suffix - the gdx symbol   cannot have a suffix',
  '587': 'Conflicting unload',
  '588': 'Compilation terminated by a Control C event',
  '589': 'Cannot have a variable/equation table statement without known   dimension',
  '590': 'Variable data record expected L,M,LO,UP,PRIOR,SCALE,...',
  '591': 'PRIOR not allowed with cont variables',
  '592': 'SCALE not allowed with discrete variables',
  '593': 'Closing / missing on variable/equation data statement',
  '594': 'Exponent too small - rejected  $offdigit can be used to replace with EPS',
  '595': 'Exponent very small  $offdigit can be used to accept small values',
  '596': 'PRIOR not allowed with equations',
  '597': 'This $if statement is ambiguous. The original or preprocessed linecontains $if NOT == . Use one of the following ways to correct     $if  NOT \'\' ==      if you really meant NOT the operator     $if \'NOT\'   ==      if you really meant NOT the string',
  '598': 'Cannot map symbol with unknown dimension',
  '599': 'Left dimension cannot be larger than right dimension',
  '600': 'Could not match index space',
  '601': 'Left side has to be Set or Parameter type for aggregation',
  '602': 'Right side has to be Set, Parameter, Variable or Equation typeLeft side has to be of same type as right side or of type set',
  '603': 'Cannot project these different types',
  '604': 'No gradient or hessian possible with this function',
  '605': 'Gradient or hessian not allowed in equations',
  '606': 'Too many grad/hess arguments',
  '607': 'Cannot do grad/hess with this function',
  '608': 'The argument list for low and high have to have the same length',
  '609': 'Embedded values need $onembedded',
  '610': 'At least one embedded value required',
  '611': 'Overflow in embedded value calculation',
  '612': '+/- INF * EPS is undefined',
  '613': 'Should never happen',
  '614': 'Too many argument lists',
  '615': 'The closing $offverbatim is missing',
  '616': '$onverbatim already set',
  '617': '$offverbatim without a matching $onverbatim',
  '618': 'The closing $offverbatim missing in previous include file',
  '619': 'ID expected',
  '620': '--id=val parameters not touched inside programuse $show to see all defined strings',
  '621': 'Unknown function suffix - allowable are   Value, Grad, Hess, GradN, HessN, Low, High, GradL, GradH',
  '622': 'Illegal system.ident, #.ident or set.ident structure',
  '623': 'No suffix allowed on system.ident, #.ident or set.ident structure',
  '624': 'No previous "onput"',
  '625': '"offput" expected',
  '626': '"onput" without an active PUT file',
  '627': '"onput" inside an active PUT context   with uncertain status, use , or /   to clarify status',
  '628': 'Missing space after ident',
  '629': 'Unknown system.xxxx in declaration context   entered as Empty   SystemConstants is a list of all entries',
  '630': 'System Environment Variable does not exist',
  '631': 'Ident has to be terminated by space',
  '632': 'Could not set system environment',
  '633': 'Prefixing the path failed',
  '634': 'A $if SET/ENV... with an item that is not a proper ident',
  '635': 'Cannot insert its own model list',
  '636': 'Model data list has not been initialized',
  '637': 'Inserted model list items exists already',
  '638': 'Suffix has been used already',
  '639': 'Bad character in string - non printable characters/control   characters having ordinal value < 32',
  '640': 'Not a model identifier',
  '641': 'Unknown symbol in set.ident or #.ident',
  '642': 'set.ident or #.ident not a set',
  '643': 'set.ident or #.ident cannot insert itself',
  '644': 'set.ident or #.ident has undefined data',
  '645': 'scalar assignments have to be type compatible',
  '646': 'Subtypes have to be the same',
  '647': 'Start skipping input',
  '648': 'End skipping input',
  '649': 'Domain violation when loading from GDX file',
  '650': 'Ord type functions only work with controlling sets not with maps',
  '651': 'Ord type functions can only be referenced with a one dimensional set',
  '652': 'Cannot unload a predefined type at compile time',
  '653': 'The left side of an equation cannot be a set expression',
  '654': 'The right side of an equation cannot be a set expression',
  '655': 'Missing model arguments for loadhandle',
  '656': 'Compress/Decompress source file name missing',
  '657': 'Compress/Decompress target file name missing',
  '658': 'Compress/Decompress operation failed, see log',
  '659': 'Error in evaluation',
  '660': 'Error in evaluation of left expression',
  '661': 'Error in evaluation of right expression',
  '662': 'Closing } or ] missing in constant expression',
  '663': 'Error in constant evaluation',
  '664': 'Bad GAMS symbol',
  '665': 'Missing == for string == string',
  '666': 'Missing string following ==',
  '667': 'Symbol does not have dimensions',
  '668': '$if [NOT] unquoted command is ambigous, use quotes around   expression',
  '669': 'identfier expected',
  '670': '$endif without an active $ifthen statement',
  '671': '$elseif/else without an active $ifthen statement',
  '672': 'Could not find matching $endif following $ifthen, the $endif  has to be in the same file as the $ifthen.',
  '673': '$ifthen nestinglevel has been exeeded',
  '674': 'Could not find $elseif/else/endif',
  '675': 'Closing $endif missing',
  '676': 'IfThen and  ElseIf/Else/EndIF/ tags to not match',
  '677': '$SYS.xxxxxx% unknown field - EMPinfo LMinfo',
  '681': 'Constant evaluation: STACK_LOW',
  '682': 'Constant evaluation: STACK_HIGH',
  '683': 'Constant evaluation: EXP_MISSING',
  '684': 'Constant evaluation: BAD_CHAR',
  '685': 'Constant evaluation: MISSING_LEFT_PAR',
  '686': 'Constant evaluation: MISSING_RIGHT_PAR',
  '687': 'Constant evaluation: TOO_FEW_ARGS',
  '688': 'Constant evaluation: BAD_SYMBOL',
  '689': 'Constant evaluation: SYNTAX_ERR',
  '690': 'Constant evaluation: UNKNOWN_IDENT',
  '691': 'Constant evaluation: BAD_RETURN_STACK',
  '692': 'Constant evaluation: EXP_TOO_BIG',
  '693': 'Constant evaluation: FPU EXCEPTION',
  '694': 'Constant evaluation: TOO_MANY_ARGS',
  '695': 'Constant evaluation: WRONG_IDENT_TYPE',
  '696': 'Constant evaluation: NO_VALUE_FOR_IDENT',
  '697': 'Constant evaluation: MISSING_IDENT',
  '698': 'Constant evaluation: VALUE_OUT_OF_RANGE',
  '699': 'Constant evaluation: OTHER_EXCEPTION',
  '700': 'Constant evaluation: MP_MISSING_COMMA',
  '701': 'Constant evaluation: MP_BAD_UNQUOTED_STRING',
  '702': 'keep space for above',
  '710': 'Variable/Equation data definition with wrong suffix   possible ones are: L M LO UP FX (L,LO,UP) SCALE PRIOR',
  '711': 'Discret variables cannot have SCALE',
  '712': 'Only Discret variable can have PRIOR',
  '713': 'Cannot have var/equ data statements with maxdim dimension',
  '714': 'Set expected for matching',
  '715': 'No data assigned',
  '716': ', : or ) expected',
  '717': 'Dimension too large',
  '718': 'Matching dimension are different',
  '719': 'Match with itself not allowed',
  '720': 'Not enough arguments',
  '721': '$macro without data',
  '722': '$macro without a legal ident - rest of line ignored',
  '723': '$macro definition had errors - message inserted',
  '724': '$macro identifier already in use',
  '725': '$macro name has illegal extension',
  '726': '$macro expansion error - skip over text',
  '727': '$macro expansion error - last skipped positon',
  '728': 'tuple or map under control already',
  '729': '$macro expansion will cause line overflow - no expansion',
  '730': '$macro is hidden and cannot be expanded',
  '731': 'Cannot assign to a macro',
  '732': 'Too manu edits on one single line - possible recursion in macro calls   compilation will be terminated',
  '733': 'abort.noerror expected',
  '734': 'Too many nested macro expansions - skip of macro ident',
  '735': 'Macro cannot have a suffix - no expansion',
  '736': 'Abort because elapsed time > ETlim',
  '737': 'Legal mappings are < <=',
  '738': 'Legal permutations are >',
  '739': 'Left side dimension of permutation not 1+2*dim_right_side',
  '740': 'Permutations have to be of type SET or PARAMETER',
  '741': 'Permutations have to be of the same type',
  '742': 'Left side dimension of permutation not 1+dim_right_side',
  '743': 'Cannot permute scalar values',
  '744': 'Domain violation on permutation',
  '745': 'Multiple MAX/MIN directives',
  '746': 'The scenario definition expects a set',
  '747': 'No MAX/MIN with short form solve statement',
  '748': 'Model name expected - SOLVE modelid ......   rest of statement ignored',
  '749': 'Multiple USING clause',
  '750': 'Unknown scenario data',
  '751': 'Multiple scenario definitions',
  '752': '.local not allowed in a reference context',
  '753': '.local nested too deep - use $onlocal to remove scoping limit',
  '754': 'Unknown prefix in %prefix.xxxx%. Has to be one of the following:   SYSTEM GAMS SYSENV SYS EMP LM SOLPRINT HANDLESTATUS SOLVELINK   SOLVESTAT MODELSTAT',
  '755': 'Unknown field in %SOLPRINT.xxx%. Has to be one of the following:   (0) Summary, (1) Report, (2) Quiet',
  '756': 'Unknown field in %HANDLESTATUS.xxx%. Has to be one of the following:   (0) Unknown, (1) Running, (2) Ready, (3) Failure',
  '757': 'Unknown field in %SOLVELINK.xxx%. Has to be one of the following:   (0) Chain Script, (1) Call Script,    (2) Call Module,   (3) Async Grid,  (4) Async Simulate, (5) Load Library',
  '758': 'Unknown field in %SOLVESTAT.xxx%. Has to be one of the following:    (1) Normal Completion    (2) Iteration Interrupt    (3) Resource Interrupt    (4) Terminated By Solver    (5) Evaluation Interrupt    (6) Capability Problems    (7) Licensing Problems    (8) User Interrupt    (9) Setup Failure   (10) Solver Failure   (11) Internal Solver Failure   (12) Solve Processing Skipped   (13) System Failure',
  '759': 'Unknown field in %MODELSTAT.xxx%. Has to be one of the following:    (1) Optimal    (2) Locally Optimal    (3) Unbounded    (4) Infeasible    (5) Locally Infeasible    (6) Intermediate Infeasible    (7) Intermediate Nonoptimal    (8) Integer Solution    (9) Intermediate Non-Integer   (10) Integer Infeasible   (11) Licensing Problem   (12) Error Unknown   (13) Error No Solution   (14) No Solution Returned   (15) Solved Unique   (16) Solved   (17) Solved Singular   (18) Unbounded - No Solution   (19) Infeasible - No Solution',
  '760': 'Tab character found; too much data -- rest of line ignored',
  '761': 'Aliased sets have to be of dimension one',
  '762': 'Dimension of first element does not match declaration',
  '763': 'Numeric field missing in <element> * <element> list',
  '764': 'Could not extract number in <element> * <element> list',
  '765': 'Size of small number string too large in <element> * <element> list',
  '766': 'Larger number string starts with \'0\' in <element> * <element> list',
  '767': 'Unexpected symbol will terminate the loop - symbol replaced by )',
  '768': 'Matching \':\' and unordered sets may create unexpected results',
  '769': '$ElseIf without an active $IfThen',
  '770': 'Reorientation can only be used with -equ.var pairs',
  '771': 'Reorientation can only be used with =L= or =G= equations',
  '772': 'execute.async or execute.sync expected',
  '773': 'Library function already defined',
  '774': 'Scenario data set has no data',
  '775': 'No assignment to scenario data set allowed',
  '776': 'Unknown symbol in position one in scenario dictionary',
  '777': 'Unknown action key in position two in scenario dictionary',
  '778': 'Unknown symbol in position three in scenario dictionary',
  '779': 'Symbol in position one not of type parameter in scenario dictionary',
  '780': 'Symbol in position one not of type variable in scenario dictionary',
  '781': 'Symbol in position one not of type var or equ in scenario dictionary',
  '782': 'Symbol in position three not of type parameter in scenario dictionary',
  '783': 'Library version is more recent than can be read',
  '784': 'Symbol in position three in scenario dictionary has no data',
  '785': 'Scenario symbol not a set',
  '786': 'Scenario symbol has no data',
  '787': 'Dimension of scenario symbol plus dimension of symbol in position   one exceeds maximum',
  '788': 'Symbol in position one in scenario dictionary has no data',
  '789': 'Dimension of symbol in position one in scenario dict unkown',
  '790': 'Symbol dimension mismatch',
  '791': 'Scenario record missing in scenario dictionary',
  '792': 'Last position of scenario record needs to be blank',
  '793': 'Multiple scenario records in scenario dictionary',
  '794': 'No scenario updaters in scenario dictionary',
  '795': 'Domain violation for symbol in scenario dictionary',
  '796': 'Some symbols in position one in scenario dictionary are not used in   model',
  '797': 'Multiple opt records in scenario dictionary',
  '798': '$call.xxx with illegal suffix - $call.async or $call.sync',
  '799': '\'equation\' expected',
  '800': 'conflicting equation type declaration',
  '801': 'conflicting equation type definition',
  '802': 'Variable type not allowed in logic equation',
  '803': 'Logic equations can only have boolean operators but ** used',
  '804': 'Logic equations can only have boolean operators but * or / used',
  '805': 'Logic equations can only have boolean operators but + or - used',
  '806': 'Logic equations with relational operations',
  '807': 'Logic equation with SUM operators',
  '808': 'Logic equation with function calls',
  '809': 'The ident.tl item has to be a controlling LOOP set',
  '810': 'Solve statement needs a USING clause',
  '811': 'Direction Maximum/Minimum is missing',
  '812': 'Solve keys expected - USING MAX/MIN SCENARIO',
  '813': 'Cannot have max/min with short form MCP or EMP',
  '814': 'GDX container with UNDF data values - use $onUNDF to allow',
  '815': 'Function used before, cannot use name in alias',
  '816': 'Cannot remove equ.var pair from model list, only equ',
  '817': 'Cannot remove reoriented -equ.var pair, only equ',
  '818': 'Wrong suffix - allowed .l, .m, .lo, .ub, .scale, .prior',
  '819': 'Cannot mix PARAM,LOWER,UPPER,FIXED and RANDVAR in scenario dictionary',
  '820': 'Symbol in position one in scenario dictionary not allowed twice with   same action',
  '821': 'Symbol in position one in scenario dictionary not allowed with both   fixed and lower/upper',
  '822': 'Symbol in position three in scenario dictionary not allowed twice   in write section',
  '823': 'PowerSet: unknown dimension or missing domains',
  '824': 'PowerSet: dimension of power set too small',
  '825': 'PowerSet: universal domains not allowed',
  '826': 'PowerSet: base or exponent sets have less than two entries',
  '827': 'PowerSet: resulting index set too small - see example below          set s /../,b /../          $eval n power(card(b),card(s))              pow(n,s,b) / system.PowerSetLeft /',
  '828': 'PowerSet: the size of the resulting structure is too large',
  '829': 'The first domain set on a permutation cannot be the universe (*)',
  '840': 'Last unused message: change maxerrmsg in ctv.pas',
  '999': '*** SENTINEL ***         1         2         3         4         5         6123456789012345678901234567890123456789012345678901234567890123456789lines are truncated beyond 69 when read into gams'
};